config/routes.rb
Rails.application.routes.draw do
  
  get 'search/:query' => "search#index", as: :search
  post 'search/post' => "search#post", as: :search_post

  devise_for :users
  resources :tags

  resources :authors

  get 'home/index'

  get 'quotes/about/:tag_name' => 'tags#quotes', as: :quotes_by_tag_name

  get 'quotes/by/:author_name' => 'authors#quotes', as: :quotes_by_author_name

  get 'feed' => 'authors#feed'

  resources :quotes

  root 'home#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base

	# Converts blank fields to null values
	nilify_blanks
	belongs_to :author
	has_and_belongs_to_many :tags


	# Gets the youtube video ID so we can embed it in the iframe
	def youtube_video_id		
		if self.video_url.nil?
			nil
		else
			self.video_url.rpartition('/').last
		end

	end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new]
  before_action :set_quote, only: [:show, :edit, :update, :destroy]
  before_action :set_display_comments, only: [:show]

  # GET /quotes
  # GET /quotes.json
  def index
    redirect_to :root
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @pageTitle = "#{@quote.quote} - #{@quote.author.name}"
  end

  # GET /quotes/new
  def new

    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    puts quote_params
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:quote, :author_id, :image_url, :video_url, :tag_ids => [])
    end

    def set_display_comments
      @show_comments = true
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br>
    <%= f.text_area :quote %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.select :author_id, options_for_select(Author.all.map{|s|[s.name, s.id]}) %>
  </div>

  <div class="field">
    <%= f.label :tags %><br>
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url%>
  </div>

  <div class="field">
    <%= f.label :video_url %><br>
    <%= f.text_field :video_url%>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Author</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.quote %></td>
        <td><%= link_to quote.author.name, quotes_by_author_name_path( quote.author.name )  %></td>
        <td>

          <% quote.tags.each do |tag| %>
            <%= tag.name %>
          <% end %>
        </td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<div class='row'>

	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-body">
						
				<% if @quote.youtube_video_id %>
					<iframe width="420" height="315" src="https://www.youtube.com/embed/<%= @quote.youtube_video_id %>" frameborder="0" allowfullscreen class='quote_media'></iframe>
				<% end %>

				<% if @quote.image_url %>
					<%= image_tag @quote.image_url, {class: "quote_media"} %>
				<% end %>
					<blockquote>
					<p>
						<%= @quote.quote %> - <%= link_to @quote.author.name, quotes_by_author_name_path( @quote.author ) %>
						<br />
					</p>
				</blockquote>
			</div>

			<div class="panel-footer">
				<div class='row'>
					<div class='col-md-7'>
						<% @quote.tags.each do | tag | %>
							<%=link_to(tag.name, quotes_by_tag_name_path(tag.name))%>
						<% end %> 	
					</div>
					<div class='col-md-5 text-right'>
						<!-- TODO: add tags as hash tags to the data-title -->
						<% if Rails.env.development? %>
							<div class="addthis_sharing_toolbox"
							data-url='<%= "http://#{request.host}:#{request.port}#{quote_path(@quote)}" %>'
							data-title='<%= @quote.quote %>'></div>
						<% else %>

						<div class="addthis_sharing_toolbox"
							data-url='<%= "http://#{request.host}#{quote_path(@quote)}" %>'
							data-title='<%= @quote.quote %>'></div>

						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class='col-md-4'>
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<!-- QE: -->
		<ins class="adsbygoogle"
		     style="display:inline-block;width:300px;height:250px"
		     data-ad-client="ca-pub-4629001980480125"
		     data-ad-slot="2661263931"></ins>
		<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
		</script>
	</div>
</div>