config/routes.rb
Rails.application.routes.draw do
  
  get 'search/:query' => "search#index", as: :search
  post 'search/post' => "search#post", as: :search_post

  devise_for :users
  resources :tags

  resources :authors

  get 'home/index'

  get 'quotes/about/:tag_name' => 'tags#quotes', as: :quotes_by_tag_name

  get 'quotes/by/:author_name' => 'authors#quotes', as: :quotes_by_author_name

  get 'feed' => 'authors#feed'

  resources :quotes

  root 'home#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
	extend FriendlyId

	friendly_id :name, use: :slugged
	has_many :quotes
	has_and_belongs_to_many :tags


	def self.popularAuthors
		Author.where(id:[12906,12582,4470,12948,7483,4362,11625,7391,4426])
	end


	def self.search(search)
	  wildcard_search = "%#{search}%"
	  where("name LIKE ?", wildcard_search)
	end
end


 

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy, :quotes]
  before_action :set_display_comments, only: [:show, :quotes]

  # GET /authors
  # GET /authors.json
  def index
    @authors, @alphaParams = Author.paginate(:page => params[:page]).alpha_paginate(params[:letter], {db_mode: true, db_field: "name",default_field:'a', js: false})
    @pageTitle = "Quotes by famous authors | QuoteEstate"
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def quotes
    @quotes = Quote.joins(:author).where( "authors.slug" => params[:author_name] ).paginate(:page => params[:page])
    @pageTitle = "Famous quotes by #{@author.name}"
  end

  def feed
    @authors = Author.all.limit(100)
    respond_to do |format|
      format.rss  { render :layout => false }
    end
  end


# select * from quotes
# left join authors
# on quotes.author_id = authors.id
# where authors.name = 'Steve Jobs'


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.friendly.find(params[:author_name])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end

    def set_display_comments
      @show_comments = true
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<%= alphabetical_paginate @alphaParams %>

<div id="pagination_table">
<% @authors.each do |author| %>
  <%= link_to author.name, quotes_by_author_name_path(author) %><br />
<% end %>
</div>

<%= will_paginate @authors %>



<% if current_user %>
	<br />
  <%=  link_to 'New Author', new_author_path %>
<% end %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/quotes.html.erb
<h1>Quotes by <%= @author.name %></h1>

<% @quotes.each_slice(2) do |quotes|%>
	<div class="row">
		<% quotes.each do |quote| %>
		<div class="col-md-6">
				<div class="panel panel-default">
					<div class="panel-body">
						
						<% if quote.youtube_video_id %>
							<iframe width="420" height="315" src="https://www.youtube.com/embed/<%= quote.youtube_video_id %>" frameborder="0" allowfullscreen class='quote_media'></iframe>
						<% end %>

						<% if quote.image_url %>
							<%= image_tag quote.image_url, {class: "quote_media"} %>
						<% end %>
						<p>
							<%= quote.quote %> - <%=  link_to quote.author.name, quotes_by_author_name_path( quote.author ) %><br />
						</p>

						<p class='text-right'>
							<%= link_to "Permalink", quote_path( quote ), {class:'text-muted'} %>
						</p>
						
					</div>
					<div class="panel-footer">
						<div class='row'>
							<div class='col-md-7'>
								<% quote.tags.each do | tag | %>
									<%=link_to(tag.name, quotes_by_tag_name_path(tag.name))%>
								<% end %> 	
							</div>
							<div class='col-md-5 text-right'>
								<!-- TODO: add tags as hash tags to the data-title -->
								<% if Rails.env.development? %>
									<div class="addthis_sharing_toolbox"
									data-url='<%= "http://#{request.host}:#{request.port}#{quote_path(quote)}" %>'
									data-title='<%= quote.quote %>'></div>
								<% else %>

								<div class="addthis_sharing_toolbox"
									data-url='<%= "http://#{request.host}#{quote_path(quote)}" %>'
									data-title='<%= quote.quote %>'></div>

								<% end %>
							</div>
						</div>

					</div>

				</div>

			</div>

		<% end %>

	</div>

<% end %>

<%= will_paginate @quotes %>

<div class='row'>
	<div class='col-md-12'>
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<!-- QE: Sky below main content -->
		<ins class="adsbygoogle"
		     style="display:inline-block;width:728px;height:90px"
		     data-ad-client="ca-pub-4629001980480125"
		     data-ad-slot="5246947131"></ins>
		<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
		</script>
	</div>
</div>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>