config/routes.rb
Rails.application.routes.draw do
  
  get 'search/:query' => "search#index", as: :search
  post 'search/post' => "search#post", as: :search_post

  devise_for :users
  resources :tags

  resources :authors

  get 'home/index'

  get 'quotes/about/:tag_name' => 'tags#quotes', as: :quotes_by_tag_name

  get 'quotes/by/:author_name' => 'authors#quotes', as: :quotes_by_author_name

  get 'feed' => 'authors#feed'

  resources :quotes

  root 'home#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :quotes


	def self.popularTags
		Tag.where(id:[1,2,3,5,8,19,31,33,69,72,210])
	end

	def self.search(search)
	  wildcard_search = "%#{search}%"
	  where("name LIKE ?", wildcard_search)
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new]
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags, @alphaParams = Tag.paginate(:page => params[:page]).alpha_paginate(params[:letter], {db_mode: true, db_field: "name",default_field:'a', js: false})
    @pageTitle = "Quotes about love, life, hapiness, sports, motivation and more."
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #GET /quotes/abouts/:tag
  def quotes
    @quotes = Quote.joins(quotes_tags: :tag).where( "tags.name" => params[:tag_name] ).paginate(:page => params[:page])
    @pageTitle = "Famous quotes about #{params[:tag_name]}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Categories</h1>


<%= alphabetical_paginate @alphaParams %>

<div id="pagination_table">
	<% @tags.order(:name).each do |tag| %>
	    <%= link_to tag.name, quotes_by_tag_name_path(tag.name) %><br />
	<% end %>
</div>

<%= will_paginate @tags %>

<br>
<% if current_user %>
  <%= link_to 'New Tag', new_tag_path %>
<% end %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/quotes.html.erb
<h1>Quotes about <%= params[:tag_name] %></h1>

<% @quotes.each_slice(2) do |quotes|%>
	<div class="row">
		<% quotes.each do |quote| %>
			<div class="col-md-6">
				<div class="panel panel-default">
					<div class="panel-body">
						<p>
							"<%= quote.quote %>"<br />
							- <%= link_to quote.author.name, quotes_by_author_name_path( quote.author ) %>
						</p>

						<p class='text-right'>
							<%= link_to "Permalink", quote_path( quote ), {class:'text-muted'} %>
						</p>
						
					</div>
					<div class="panel-footer">
						<div class='row'>
							<div class='col-md-7'>
								<% quote.tags.each do | tag | %>
									<%= link_to(tag.name, quotes_by_tag_name_path(tag.name))  %>
								<% end %> 	
							</div>
							<div class='col-md-5 text-right'>
								<!-- TODO: add tags as hash tags to the data-title -->
								<% if Rails.env.development? %>
									<div class="addthis_sharing_toolbox"
									data-url='<%= "http://#{request.host}:#{request.port}#{quote_path(quote)}" %>'
									data-title='<%= quote.quote %>'></div>
								<% else %>

								<div class="addthis_sharing_toolbox"
									data-url='<%= "http://#{request.host}#{quote_path(quote)}" %>'
									data-title='<%= quote.quote %>'></div>

								<% end %>
							</div>
						</div>

					</div>

				</div>
			</div>
		<% end %>

	</div>

<% end %>

<%= will_paginate @quotes %>


<div class='row'>
	<div class='col-md-12'>
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<!-- QE: Sky below main content -->
		<ins class="adsbygoogle"
		     style="display:inline-block;width:728px;height:90px"
		     data-ad-client="ca-pub-4629001980480125"
		     data-ad-slot="5246947131"></ins>
		<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
		</script>
	</div>
</div>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>